const express = require("express");
const checkAuth = require("./../middleware/checkAuth.js");
const { addSpecialUsers, deleteUser } = require("./../controllers/admin.js");

const router = express.Router();

/**
 * @swagger
 * /api/v1/admin/add-special-user:
 *   post:
 *     summary: Gives special privilege to the user
 *     description: Gives the user the special privelege to extend the ending date of his task beyond the max date of three months
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               email:
 *                 type: string
 *                 description: The user's email
 *                 example: johndoe@gmail.com
 *     responses:
 *       201:
 *         description: User given special privilege
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 _id:
 *                   type: string
 *                   description: The user's special privelege ID
 *                   example: 34678767h898jh888
 *                 userId:
 *                   type: string
 *                   description: The user ID
 *                   example: 34678767h898jh888
 *                 email:
 *                   type: string
 *                   description: The user's email
 *                   example: johndoe7@gmail.com
 *                 createdAt:
 *                   type: string
 *                   description: Date the special privilege was given. It is auto generated by the database
 *                   example: 2024-07-06T15:49:05.191+00:00
 *                 updatedAt:
 *                   type: string
 *                   description: Date the special privilege was updated. It is auto generated by the database
 *                   example: 2024-07-06T15:49:05.191+00:00
 *       401:
 *         description: Access not authorized. User not an admin.
 *       400:
 *         description: email not provided || User not registered || User already added.
 *
 */

router.post("/add-special-user", checkAuth, addSpecialUsers);

/**
 * @swagger
 * /api/v1/admin/delete-user:
 *   delete:
 *     summary: Endpoint for deleting users
 *     description: Endpoint for deleting users
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               email:
 *                 type: string
 *                 description: The user's email
 *                 example: johndoe@gmail.com
 *     responses:
 *       204:
 *         description: User deleted successfully
 *       401:
 *         description: Access not authorized. User not an admin.
 *       400:
 *         description: email not provided.
 *       404:
 *         description: User not found
 */

router.delete("/delete-user", checkAuth, deleteUser);

module.exports = router;
